# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: wiz@0
  inputs:
    command: 'iac'
    clientid: $(WIZ_CLIENT_ID)
    secret: $(WIZ_CLIENT_SECRET)
    path: 'terraform'
    policyHitsOnly: true
    scanPolicies: 'SecCloudDev-Demo-Audit-Misconfigurations,SecCloudDev-Demo-Audit-Secrets'
    scanSecrets: true
