# https://docs.wiz.io/wiz-docs/docs/github-pipeline

name: 'wizcli'

on: 
  pull_request:
    branches: 
    - main

jobs:
  wiz-iac-scan:
    name: 'WizCLI IaC Scan'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "../../terraform"             # Set the relative path in the repo to scan.
      CICD_POLICY: "Shift-Left-Demo-IaC"       # Set the Wiz CI/CD policy to use.
      OUTPUT_FILE: "wiz-iac-scan-results.json" # Set the output file to use.

    steps:
    # This action checks-out your repository, so third-party tools can access it.
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download WizCLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      # Credentials for a Wiz Service Account (CLIENT ID and SECRET) is required to authenticate to Wiz.
      # Wiz Service Account permissions: create:security_scans.
      run: ./wizcli auth --id "${WIZ_CLIENT_ID}" --secret "${WIZ_CLIENT_SECRET}"
      # Secrets allow you to store sensitive information (credentials) in your organization, repository, or repository environments.
      env:
        WIZ_CLIENT_ID: ${{secrets.WIZ_CLIENT_ID}}
        WIZ_CLIENT_SECRET: ${{secrets.WIZ_CLIENT_SECRET}}

    - name: Run WizCLI IaC Scan 
      run: ./wizcli iac scan --path "${SCAN_PATH}" --policy "${CICD_POLICY}" --policy-hits-only --output "${OUTPUT_FILE}",sarif,true

    # This action uploads SARIF files to your repository, so you can see code scanning alerts from third-party tools.
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${OUTPUT_FILE}
      continue-on-error: true
