# Requires credentials for a Wiz Service Account to authenticate to Wiz. 
# For your demo use, specify a Wiz Service Account and CI/CD Policies in CSA-Prod.
# Reference: https://docs.wiz.io/wiz-docs/docs/service-accounts-settings
#
# Wiz Service Account permissions: create:security_scans, and update:security_scans (only when using "wizcli docker tag").
# Reference: https://docs.wiz.io/wiz-docs/docs/github-pipeline
#
# Store CLIENT_ID as secrets.WIZ_CLIENT_ID and SECRET as secrets.WIZ_CLIENT_SECRET
# Reference: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

name: 'wiz-image-scan'

on: 
  pull_request:
    branches: 
    - main
    # Modify this to match your demo use case. For example:
    # To scan all Dockerfiles, change to: - 'images/**'
    paths:
    - 'images/Dockerfile'

jobs:
  wiz-image-scan:
    name: 'WizCLI Image Scan'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: 'images'
      # Modify this to match your demo use case. For example, to Audit rather than Block:
      # CICD_POLICIES: 'SL-Demo-Secrets,SL-Demo-Vulnerabilities'
      CICD_POLICIES: 'SL-Demo-Secrets-Block,SL-Demo-Vulnerabilities-Block'
      OUTPUT_FILE: 'wiz-image-scan-results.json'
      IMAGE: 'wizard/wiz-example-image'
      TAG: ${{ github.run_number }}
      # Requires configuration in Docker Hub (or another registry) to demo "wizcli docker tag".
      # https://github.com/marketplace/actions/docker-login
      ENABLE_WIZ_DOCKER_TAG: 'false'

    steps:
    # This action checks-out your repository, so third-party tools can access it.
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      if: ${{ env.ENABLE_WIZ_DOCKER_TAG == 'true' }}
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker Image
      run: docker build "${SCAN_PATH}" -t "${IMAGE}:${TAG}"

    - name: Download WizCLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "${WIZ_CLIENT_ID}" --secret "${WIZ_CLIENT_SECRET}"
      # Secrets allow you to store sensitive information (credentials) in your organization, repository, or repository environments.
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    - name: Run WizCLI (Docker) Image Scan
      run: ./wizcli docker scan --image "${IMAGE}:${TAG}" --dockerfile "${SCAN_PATH}/Dockerfile" --driver mountWithLayers --policy "${CICD_POLICIES}" --policy-hits-only --output "${OUTPUT_FILE}",sarif,true

    - name: Push Docker Image
      if: ${{ env.ENABLE_WIZ_DOCKER_TAG == 'true' }}
      run: docker push "${IMAGE}:${TAG}"

    - name: WizCLI Docker Tag
      if: ${{ env.ENABLE_WIZ_DOCKER_TAG == 'true' }}
      run: |
        docker images list
        docker images --digests
        ./wizcli docker tag --image "${IMAGE}:${TAG}"

    # This action uploads SARIF files, so you can see code scanning alerts from third-party tools in your repository.
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${OUTPUT_FILE}
      continue-on-error: true
