# Requires credentials for a Wiz Service Account to authenticate to Wiz.
# For your demo use, specify a Wiz Service Account and CI/CD Policies in CSA-Prod.
# Reference: https://docs.wiz.io/wiz-docs/docs/service-accounts-settings
#
# Wiz Service Account permissions: create:security_scans, and update:security_scans (only when using "wizcli docker tag").
# Reference: https://docs.wiz.io/wiz-docs/docs/github-pipeline
#
# Store CLIENT_ID as secrets.WIZ_CLIENT_ID and SECRET as secrets.WIZ_CLIENT_SECRET
# Reference: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

name: 'wiz-image-scan'

on: [pull_request]

jobs:
  wiz-cli-image-scan:
    name: 'WizCLI Image Scan'
    env:
      SCAN_PATH: 'container'
      CICD_IAC_POLICIES: 'SecCloudDev-Demo-Block-Misconfigurations,SecCloudDev-Demo-Block-Secrets'
      CICD_IMG_POLICIES: 'SecCloudDev-Demo-Block-Secrets,SecCloudDev-Demo-Block-Vulnerabilities'
      IMAGE: 'wizard/wiz-example-image'
      TAG: ${{ github.run_number }}

    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download WizCLI
      run: |
        curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "${WIZ_CLIENT_ID}" --secret "${WIZ_CLIENT_SECRET}"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    - name: Build the Docker Image
      run: |
        docker build "${SCAN_PATH}" -t "${IMAGE}:${TAG}"

    - name: Run WizCLI Docker Scan
      run: |
        ./wizcli docker scan --image "${IMAGE}:${TAG}" --dockerfile "${SCAN_PATH}/Dockerfile" --policy "${CICD_IMG_POLICIES}" --policy-hits-only
